paths:
  - ./src
layers:
  - name: Application
    collectors:
      - type: className
        regex: ^IntegerNet\\InventoryApi\\Application\\
  - name: Infrastructure
    collectors:
      - type: className
        regex: ^IntegerNet\\InventoryApi\\Infrastructure\\
      - type: className
        regex: ^Psr
      - type: className
        regex: ^React
      - type: className
        regex: ^RingCentral
  - name: Domain
    collectors:
      - type: className
        regex: ^IntegerNet\\InventoryApi\\Domain\\
      - type: className
        regex: ^EventSauce
ruleset:
  Application:
    - Domain
    - Infrastructure
  Infrastructure:
    - Domain
  Repository:
